export const SET_SURVEY = "SET_SURVEY";
export const SET_LOADING = "SET_LOADING";
export const SET_RESPONDENT = "SET_RESPONDENT";
export const SET_IS_PARTICIPATE = "SET_IS_PARTICIPATE";
export const ADD_QUERY_ANSWER = "ADD_QUERY_ANSWER";
export const SET_QUERYS = "SET_QUERYS";
