export const SET_SURVEY = "SET_SURVEY";
export const SET_LOADING = "SET_LOADING";
export const SET_QUERYS = "SET_QUERYS";
export const ADD_QUERY_ANSWER = "ADD_QUERY_ANSWER";
export const SET_SURVEY_PARTICIPATE = "SET_SURVEY_PARTICIPATE";
export const SET_SURVEY_RESPONDENT_INFO = "SET_SURVEY_RESPONDENT_INFO";
