export const SET_MY_SURVEYS = "SET_MY_SURVEYS";
export const SET_SURVEY = "SET_SURVEY";
export const SET_SURVEY_TITLE = "SET_SURVEY_TITLE"
export const SET_SURVEY_QUERY_TITLE = "SET_SURVEY_QUERY_TITLE";
export const SET_SURVEY_QUERY_ANSWER_TYPE = "SET_SURVEY_QUERY_ANSWER_TYPE";
